admin:
    resource: "@adminBundle/Resources/config/routing.yml"
    prefix:   /

contactus:
    resource: "@ContactusBundle/Resources/config/routing.yml"
    prefix:   /

register:
    resource: "@RegisterBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
